// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.819
package ui

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/dimmerz92/templwind/pkg/icons"
import "github.com/dimmerz92/templwind/pkg/lib"

type ThemeToggleSize string

const (
	XSmallToggle ThemeToggleSize = "text-[24px]"
	SmallToggle  ThemeToggleSize = "text-[32px]"
	MediumToggle ThemeToggleSize = "text-[40px]"
	LargeToggle  ThemeToggleSize = "text-[48px]"
	XLargeToggle ThemeToggleSize = "text-[56px]"
)

type ThemeToggleProps struct {
	Icon icons.ThemeToggleIcon // Optional: Specifies the icon to be used, defaults to Classic
	Size ThemeToggleSize       // Optional: Specifies the icon size, defaults to MediumToggle
}

// ThemeToggle renders a clickable theme toggle icon. Best used with the DetectTheme script component to apply theme preferences on load.
// NOTE: This component requires JavaScript.
func ThemeToggle(props ThemeToggleProps) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		var templ_7745c5c3_Var2 = []any{"theme-toggle cursor-pointer inline-block leading-0", string(lib.Coalesce(props.Size, MediumToggle))}
		templ_7745c5c3_Err = templ.RenderCSSItems(ctx, templ_7745c5c3_Buffer, templ_7745c5c3_Var2...)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<label class=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(templ.CSSClasses(templ_7745c5c3_Var2).String())
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `pkg/ui/theme_toggle.templ`, Line: 1, Col: 0}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\" role=\"button\" aria-label=\"click to toggle between light and dark mode\" onkeypress=\"event.code === &#39;Space&#39; &amp;&amp; document.querySelector(&#39;#theme-toggle&#39;).click();\" tabindex=\"0\"><input type=\"checkbox\" id=\"theme-toggle\" class=\"hidden\" onclick=\"document.documentElement.classList.toggle(&#39;dark&#39;); localStorage.setItem(&#39;theme&#39;, this.checked ? &#39;dark&#39; : &#39;light&#39;);\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = icons.ThemeToggleMap[props.Icon]().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</label>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// DetectTheme will checked for a cached theme preference or derive it from the user's system preferences.
// NOTE: This is a JavaScript component.
func DetectTheme() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var4 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var4 == nil {
			templ_7745c5c3_Var4 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<script>\n\t\t// checked for a cached theme preference or derive from system\n\t\tlet theme = localStorage.getItem(\"theme\") ?? (window.matchMedia(\"(prefers-color-scheme: dark)\").matches ? \"dark\" : \"light\");\n\n\t\t// apply color theme\n\t\tdocument.documentElement.classList.toggle(\"dark\", theme === \"dark\");\n\n\t\t// check the toggle checkbox if present\n\t\tdocument.addEventListener(\"DOMContentLoaded\", () => {\n\t\t\tconst toggle = document.querySelector('#theme-toggle');\n\t\t\tif (toggle !== null) toggle.checked = theme === \"dark\";\n\t\t}, { once: true })\n\t</script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
